[target.thumbv8m.main-none-eabi]
# unimplemented
runner = 'probe-rs run --chip SF32LB52x'
# Cortex-M33 has MSPLIM, so we don't need flip-link
# linker= "flip-link"

[build]
target = "thumbv8m.main-none-eabi"

[env]
DEFMT_LOG = "info"
